name: Weekly Release

on:
  schedule:
    # 10:00 KST every Sunday.
    - cron: "0 1 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    with:
      build: ${{ github.run_number }}
      head: "0"
      target_ref: ${{ github.sha }}
      timezone: Asia/Seoul
